export default function GameCardImages() {
  const cardImages = [
    { src: "/cardFront/SpadeQ.png", matched: false },
    { src: "/cardFront/SpadeK.png", matched: false },
    { src: "/cardFront/SpadeJ.png", matched: false },
    { src: "/cardFront/Spade10.png", matched: false },
    { src: "/cardFront/Spade9.png", matched: false },
    { src: "/cardFront/Spade8.png", matched: false },
    { src: "/cardFront/Spade7.png", matched: false },
    { src: "/cardFront/Spade6.png", matched: false },
    { src: "/cardFront/Spade5.png", matched: false },
    { src: "/cardFront/Spade4.png", matched: false },
    { src: "/cardFront/Spade3.png", matched: false },
    { src: "/cardFront/Spade2.png", matched: false },
    { src: "/cardFront/Spade1.png", matched: false },
    { src: "/cardFront/Joker.png", matched: false },
    { src: "/cardFront/HeartQ.png", matched: false },
    { src: "/cardFront/HeartK.png", matched: false },
    { src: "/cardFront/HeartJ.png", matched: false },
    { src: "/cardFront/Heart10.png", matched: false },
    { src: "/cardFront/Heart9.png", matched: false },
    { src: "/cardFront/Heart8.png", matched: false },
    { src: "/cardFront/Heart7.png", matched: false },
    { src: "/cardFront/Heart6.png", matched: false },
    { src: "/cardFront/Heart5.png", matched: false },
    { src: "/cardFront/Heart4.png", matched: false },
    { src: "/cardFront/Heart3.png", matched: false },
    { src: "/cardFront/Heart2.png", matched: false },
    { src: "/cardFront/Heart1.png", matched: false },
    { src: "/cardFront/DiaQ.png", matched: false },
    { src: "/cardFront/DiaK.png", matched: false },
    { src: "/cardFront/DiaJ.png", matched: false },
    { src: "/cardFront/Dia10.png", matched: false },
    { src: "/cardFront/Dia9.png", matched: false },
    { src: "/cardFront/Dia8.png", matched: false },
    { src: "/cardFront/Dia7.png", matched: false },
    { src: "/cardFront/Dia6.png", matched: false },
    { src: "/cardFront/Dia5.png", matched: false },
    { src: "/cardFront/Dia4.png", matched: false },
    { src: "/cardFront/Dia3.png", matched: false },
    { src: "/cardFront/Dia2.png", matched: false },
    { src: "/cardFront/Dia1.png", matched: false },
    { src: "/cardFront/CloverQ.png", matched: false },
    { src: "/cardFront/CloverK.png", matched: false },
    { src: "/cardFront/CloverJ.png", matched: false },
    { src: "/cardFront/Clover10.png", matched: false },
    { src: "/cardFront/Clover9.png", matched: false },
    { src: "/cardFront/Clover8.png", matched: false },
    { src: "/cardFront/Clover7.png", matched: false },
    { src: "/cardFront/Clover6.png", matched: false },
    { src: "/cardFront/Clover5.png", matched: false },
    { src: "/cardFront/Clover4.png", matched: false },
    { src: "/cardFront/Clover3.png", matched: false },
    { src: "/cardFront/Clover2.png", matched: false },
    { src: "/cardFront/Clover1.png", matched: false },
  ];

  return ( cardImages );
}
